# Package Overview
package_name: m3mp1

# Data Files
training_data_file: bike-sharing-dataset.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: cnt

pipeline_name: bikeshare_model
pipeline_save_file: bikeshare__model_output_v

features:      # final features to be use
  - season
  - hr
  - holiday 
  - workingday 
  - weathersit
  - temp
  - atemp
  - hum
  - windspeed
  - year # generated
  - month # generated

unused_fields:  # Features to drop before pipeline
  - dteday
  - casual
  - registered
  - weekday
  - day # generated
  
# Features inside processing pipeline

dteday_var: dteday
weekday_var: weekday  
weathersit_var: weathersit

year_var: year
mnth_var: month
season_var: season
weather_var: weather
holiday_var: holiday
workingday_var: workingday
hr_var: hr

year_mapping: 
  2011: 0
  2012: 1

mnth_mapping: 
  January: 1
  February: 2
  March: 3
  April: 4
  May: 5
  June: 6
  July: 7
  August: 8
  September: 9
  October: 10
  November: 11
  December: 12

season_mapping: 
  spring: 0
  winter: 1
  summer: 2
  fall: 3

weather_mapping:
  Heavy Rain: 0
  Light Rain: 1
  Mist: 2
  Clear: 3
  
holiday_mapping:
  Yes: 0
  No: 1

workingday_mapping:
  No: 0
  Yes: 1

hr_mapping: 
  12am: 0
  1am: 1
  2am: 2
  3am: 3
  4am: 4
  5am: 5
  6am: 6
  7am: 7
  8am: 8
  9am: 9
  10am: 10
  11am: 11
  12pm: 12
  1pm: 13
  2pm: 14
  3pm: 15
  4pm: 16
  5pm: 17
  6pm: 18
  7pm: 19
  8pm: 20
  9pm: 21
  10pm: 22
  11pm: 23


feature_outlier: 
#  - dteday
  - temp
  - hum
  - windspeed
#  - casual
#  - registered
#  - cnt
#  - year
   
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 150
max_depth: 5

